name: NPM Audit

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  audit:
    name: Audit packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4
      - name: NPM Audit ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - uses: oke-py/npm-audit-action@v3
        with:
          audit_level: low
          create_issues: true
          create_pr_comments: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
          json_flag: true
