name: Unit Test
permissions:
  contents: read

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest

    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        node-version: [22.20.0, 24.x]
    #        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install NPM dependencies
        run: npm install @mapbox/node-pre-gyp
        env:
          NODE_ENV: production
          CI: true

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -qq build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev make gcc wget curl xz-utils
          sudo apt-get -qq install --yes ghostscript graphicsmagick
          sudo apt install -qq libx11-dev libxext-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libxml2-dev
          sudo wget https://imagemagick.org/archive/releases/${{vars.IMAGE_MAGIC_VERSION}}.tar.xz
          sudo tar xf ${{vars.IMAGE_MAGIC_VERSION}}.tar.xz
          sudo rm ${{vars.IMAGE_MAGIC_VERSION}}.tar.xz
          sudo sh ./${{vars.IMAGE_MAGIC_VERSION}}/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes
          sudo make -s -j4
          sudo make -s install
          sudo ldconfig /usr/local/lib

      - name: Check dependencies
        run: |
          convert -version
          gm -version
          gs -h

      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm ci --force

      - name: Test
        run: npm test
